version: 2
updates:
- package-ecosystem: gomod
  directory: "/agent"
  schedule:
    interval: weekly
    time: "11:06"
  open-pull-requests-limit: 1
  target-branch: "dev"
- package-ecosystem: gomod
  directory: "/ecs-agent"
  schedule:
    interval: weekly
    time: "00:00"
  open-pull-requests-limit: 1
  target-branch: "dev"
  ignore:
    # aws-sdk-go is upgraded manually: auto-upgrades break tests and risk breaking the agent.
    - dependency-name: "github.com/aws/aws-sdk-go"
- package-ecosystem: gomod
  directory: "/dcgm-init"
  schedule:
    interval: weekly
    time: "05:00"
  open-pull-requests-limit: 1
  target-branch: "dev"
- package-ecosystem: "github-actions"
  directory: ".github/workflows"
  schedule:
    interval: weekly
    time: "00:00"
  open-pull-requests-limit: 1
  target-branch: "dev"
