// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/amazon-ecs-agent/ecs-agent/api/appnet (interfaces: AppNetClient)

// Package mock_appnet is a generated GoMock package.
package mock_appnet

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	io_prometheus_client "github.com/prometheus/client_model/go"
)

// MockAppNetClient is a mock of AppNetClient interface.
type MockAppNetClient struct {
	ctrl     *gomock.Controller
	recorder *MockAppNetClientMockRecorder
}

// MockAppNetClientMockRecorder is the mock recorder for MockAppNetClient.
type MockAppNetClientMockRecorder struct {
	mock *MockAppNetClient
}

// NewMockAppNetClient creates a new mock instance.
func NewMockAppNetClient(ctrl *gomock.Controller) *MockAppNetClient {
	mock := &MockAppNetClient{ctrl: ctrl}
	mock.recorder = &MockAppNetClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppNetClient) EXPECT() *MockAppNetClientMockRecorder {
	return m.recorder
}

// DrainInboundConnections mocks base method.
func (m *MockAppNetClient) DrainInboundConnections(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DrainInboundConnections", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DrainInboundConnections indicates an expected call of DrainInboundConnections.
func (mr *MockAppNetClientMockRecorder) DrainInboundConnections(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DrainInboundConnections", reflect.TypeOf((*MockAppNetClient)(nil).DrainInboundConnections), arg0, arg1)
}

// GetStats mocks base method.
func (m *MockAppNetClient) GetStats(arg0, arg1 string) (map[string]*io_prometheus_client.MetricFamily, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", arg0, arg1)
	ret0, _ := ret[0].(map[string]*io_prometheus_client.MetricFamily)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockAppNetClientMockRecorder) GetStats(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockAppNetClient)(nil).GetStats), arg0, arg1)
}
